name: Rust build and E2E tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Check Rust code
      run: cargo check --all --all-features

    - name: Lint Rust code with Clippy
      run: cargo clippy --all --all-targets -- -D warnings

    - name: Format Rust code with Rustfmt
      run: cargo fmt --all -- --check

    - name: Build Rust code
      run: cargo build --release

    - name: Run API server
      run: cargo run --release &

    - name: Wait for health endpoint to be ready
      run: ./e2e/wait_for_health.sh

    - name: Test AWS endpoint
      run: ./e2e/aws.sh

    - name: Test Azure endpoint
      run: ./e2e/azure.sh

    - name: Test Fastly endpoint
      run: ./e2e/fastly.sh

    - name: Test GCP endpoint
      run: ./e2e/gcp.sh

    - name: Test Linode endpoint
      run: ./e2e/linode.sh
